ALTER TABLE SBR.ADMINISTERED_COMPONENTS MODIFY (PREFERRED_DEFINITION VARCHAR2(4000 BYTE));
ALTER TABLE SBR.VALUE_MEANINGS MODIFY 
(PREFERRED_DEFINITION VARCHAR2(4000 BYTE), 
DESCRIPTION VARCHAR2(4000 BYTE));
ALTER TABLE SBR.DEFINITIONS MODIFY (DEFINITION VARCHAR2(4000 BYTE));
ALTER TABLE SBR.PERMISSIBLE_VALUES MODIFY (MEANING_DESCRIPTION VARCHAR2(4000 BYTE));
ALTER TABLE SBREXT.CONCEPTS_EXT MODIFY (PREFERRED_DEFINITION VARCHAR2(4000 BYTE));
ALTER TABLE SBR.CD_VMS MODIFY (DESCRIPTION VARCHAR2(4000 BYTE));
ALTER TABLE SBREXT.VALID_VALUES_ATT_EXT MODIFY (DESCRIPTION_TEXT VARCHAR2(4000 BYTE));