ALTER TYPE SBREXT.DE_VALID_VALUE_T
MODIFY attribute MEANINGDESCRIPTION varchar2(4000) CASCADE;
ALTER TYPE SBREXT.VALID_VALUE_T
MODIFY attribute MeaningDescription varchar2(4000) CASCADE;
ALTER TYPE SBREXT.VALID_VALUE_T
MODIFY attribute VmAlternateDefinitions varchar2(4000) CASCADE;
