/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package nci.cadsr.persist.dao.oracle;

import java.sql.Connection;

import nci.cadsr.persist.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public DesignationsViewDao createDesignationsViewDao( Connection conn ) {
        return new DesignationsViewDaoImpl( conn );
    }

    public PermissibleValuesViewDao createPermissibleValuesViewDao( Connection conn ) {
        return new PermissibleValuesViewDaoImpl( conn );
    }

}
