/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package nci.cadsr.persist.dto;

import java.sql.Date;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class PermissibleValuesView extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "permissible_values_view";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private String pVIDSEQ;
    private String vALUE;
    private String sHORTMEANING;
    private String mEANINGDESCRIPTION;
    private Date bEGINDATE;
    private Date eNDDATE;
    private Long hIGHVALUENUM;
    private Long lOWVALUENUM;
    private Date dATECREATED;
    private String cREATEDBY;
    private Date dATEMODIFIED;
    private String mODIFIEDBY;
    private String vMIDSEQ;

    private boolean isMEANINGDESCRIPTIONModified;
    private boolean isBEGINDATEModified;
    private boolean isENDDATEModified;
    private boolean isHIGHVALUENUMModified;
    private boolean isLOWVALUENUMModified;
    private boolean isDATECREATEDModified;
    private boolean isCREATEDBYModified;
    private boolean isDATEMODIFIEDModified;
    private boolean isMODIFIEDBYModified;
    private boolean isVMIDSEQModified;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public PermissibleValuesView() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public String getPVIDSEQ() {
        return pVIDSEQ;
    }

    public void setPVIDSEQ( String _val) {
        this.pVIDSEQ = _val;
    }

    public String getVALUE() {
        return vALUE;
    }

    public void setVALUE( String _val) {
        this.vALUE = _val;
    }

    public String getSHORTMEANING() {
        return sHORTMEANING;
    }

    public void setSHORTMEANING( String _val) {
        this.sHORTMEANING = _val;
    }

    public String getMEANINGDESCRIPTION() {
        return mEANINGDESCRIPTION;
    }

    public void setMEANINGDESCRIPTION( String _val) {
        this.mEANINGDESCRIPTION = _val;
        this.isMEANINGDESCRIPTIONModified = true;
    }

    public boolean isMEANINGDESCRIPTIONModified() {
        return isMEANINGDESCRIPTIONModified;
    }

    public Date getBEGINDATE() {
        return bEGINDATE;
    }

    public void setBEGINDATE( java.util.Date _val ) {
        setBEGINDATE((Date)( _val != null ? new Date( _val.getTime()) : null ));
    }

    public void setBEGINDATE( Date _val) {
        this.bEGINDATE = _val;
        this.isBEGINDATEModified = true;
    }

    public boolean isBEGINDATEModified() {
        return isBEGINDATEModified;
    }

    public Date getENDDATE() {
        return eNDDATE;
    }

    public void setENDDATE( java.util.Date _val ) {
        setENDDATE((Date)( _val != null ? new Date( _val.getTime()) : null ));
    }

    public void setENDDATE( Date _val) {
        this.eNDDATE = _val;
        this.isENDDATEModified = true;
    }

    public boolean isENDDATEModified() {
        return isENDDATEModified;
    }

    public Long getHIGHVALUENUM() {
        return hIGHVALUENUM;
    }

    public void setHIGHVALUENUM( Long _val) {
        this.hIGHVALUENUM = _val;
        this.isHIGHVALUENUMModified = true;
    }

    public boolean isHIGHVALUENUMModified() {
        return isHIGHVALUENUMModified;
    }

    public Long getLOWVALUENUM() {
        return lOWVALUENUM;
    }

    public void setLOWVALUENUM( Long _val) {
        this.lOWVALUENUM = _val;
        this.isLOWVALUENUMModified = true;
    }

    public boolean isLOWVALUENUMModified() {
        return isLOWVALUENUMModified;
    }

    public Date getDATECREATED() {
        return dATECREATED;
    }

    public void setDATECREATED( java.util.Date _val ) {
        setDATECREATED((Date)( _val != null ? new Date( _val.getTime()) : null ));
    }

    public void setDATECREATED( Date _val) {
        this.dATECREATED = _val;
        this.isDATECREATEDModified = true;
    }

    public boolean isDATECREATEDModified() {
        return isDATECREATEDModified;
    }

    public String getCREATEDBY() {
        return cREATEDBY;
    }

    public void setCREATEDBY( String _val) {
        this.cREATEDBY = _val;
        this.isCREATEDBYModified = true;
    }

    public boolean isCREATEDBYModified() {
        return isCREATEDBYModified;
    }

    public Date getDATEMODIFIED() {
        return dATEMODIFIED;
    }

    public void setDATEMODIFIED( java.util.Date _val ) {
        setDATEMODIFIED((Date)( _val != null ? new Date( _val.getTime()) : null ));
    }

    public void setDATEMODIFIED( Date _val) {
        this.dATEMODIFIED = _val;
        this.isDATEMODIFIEDModified = true;
    }

    public boolean isDATEMODIFIEDModified() {
        return isDATEMODIFIEDModified;
    }

    public String getMODIFIEDBY() {
        return mODIFIEDBY;
    }

    public void setMODIFIEDBY( String _val) {
        this.mODIFIEDBY = _val;
        this.isMODIFIEDBYModified = true;
    }

    public boolean isMODIFIEDBYModified() {
        return isMODIFIEDBYModified;
    }

    public String getVMIDSEQ() {
        return vMIDSEQ;
    }

    public void setVMIDSEQ( String _val) {
        this.vMIDSEQ = _val;
        this.isVMIDSEQModified = true;
    }

    public boolean isVMIDSEQModified() {
        return isVMIDSEQModified;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof PermissibleValuesView))) return false;

        PermissibleValuesView _o = (PermissibleValuesView) _other;

        if ( pVIDSEQ == null ) {
            if ( _o.pVIDSEQ != null ) return false;
        }
        else if ( _o.pVIDSEQ == null || !pVIDSEQ.equals( _o.pVIDSEQ )) return false;

        if ( vALUE == null ) {
            if ( _o.vALUE != null ) return false;
        }
        else if ( _o.vALUE == null || !vALUE.equals( _o.vALUE )) return false;

        if ( sHORTMEANING == null ) {
            if ( _o.sHORTMEANING != null ) return false;
        }
        else if ( _o.sHORTMEANING == null || !sHORTMEANING.equals( _o.sHORTMEANING )) return false;

        if ( mEANINGDESCRIPTION == null ) {
            if ( _o.mEANINGDESCRIPTION != null ) return false;
        }
        else if ( _o.mEANINGDESCRIPTION == null || !mEANINGDESCRIPTION.equals( _o.mEANINGDESCRIPTION )) return false;

        if ( bEGINDATE == null ) {
            if ( _o.bEGINDATE != null ) return false;
        }
        else if ( _o.bEGINDATE == null || bEGINDATE.getTime() != _o.bEGINDATE.getTime()) return false;

        if ( eNDDATE == null ) {
            if ( _o.eNDDATE != null ) return false;
        }
        else if ( _o.eNDDATE == null || eNDDATE.getTime() != _o.eNDDATE.getTime()) return false;

        if ( hIGHVALUENUM == null ) {
            if ( _o.hIGHVALUENUM != null ) return false;
        }
        else if ( _o.hIGHVALUENUM == null || hIGHVALUENUM.longValue() != _o.hIGHVALUENUM.longValue()) return false;

        if ( lOWVALUENUM == null ) {
            if ( _o.lOWVALUENUM != null ) return false;
        }
        else if ( _o.lOWVALUENUM == null || lOWVALUENUM.longValue() != _o.lOWVALUENUM.longValue()) return false;

        if ( dATECREATED == null ) {
            if ( _o.dATECREATED != null ) return false;
        }
        else if ( _o.dATECREATED == null || dATECREATED.getTime() != _o.dATECREATED.getTime()) return false;

        if ( cREATEDBY == null ) {
            if ( _o.cREATEDBY != null ) return false;
        }
        else if ( _o.cREATEDBY == null || !cREATEDBY.equals( _o.cREATEDBY )) return false;

        if ( dATEMODIFIED == null ) {
            if ( _o.dATEMODIFIED != null ) return false;
        }
        else if ( _o.dATEMODIFIED == null || dATEMODIFIED.getTime() != _o.dATEMODIFIED.getTime()) return false;

        if ( mODIFIEDBY == null ) {
            if ( _o.mODIFIEDBY != null ) return false;
        }
        else if ( _o.mODIFIEDBY == null || !mODIFIEDBY.equals( _o.mODIFIEDBY )) return false;

        if ( vMIDSEQ == null ) {
            if ( _o.vMIDSEQ != null ) return false;
        }
        else if ( _o.vMIDSEQ == null || !vMIDSEQ.equals( _o.vMIDSEQ )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = 1130090642; // = "PermissibleValuesView".hashCode()
        _ret += pVIDSEQ == null ? 0 : pVIDSEQ.hashCode();
        _ret = 29 * _ret + (vALUE == null ? 0 : vALUE.hashCode());
        _ret = 29 * _ret + (sHORTMEANING == null ? 0 : sHORTMEANING.hashCode());
        _ret = 29 * _ret + (mEANINGDESCRIPTION == null ? 0 : mEANINGDESCRIPTION.hashCode());
        _ret = 29 * _ret + (bEGINDATE == null ? 0 : (int)bEGINDATE.getTime());
        _ret = 29 * _ret + (eNDDATE == null ? 0 : (int)eNDDATE.getTime());
        _ret = 29 * _ret + (hIGHVALUENUM == null ? 0 : (int)(hIGHVALUENUM ^ (hIGHVALUENUM >>> 32)));
        _ret = 29 * _ret + (lOWVALUENUM == null ? 0 : (int)(lOWVALUENUM ^ (lOWVALUENUM >>> 32)));
        _ret = 29 * _ret + (dATECREATED == null ? 0 : (int)dATECREATED.getTime());
        _ret = 29 * _ret + (cREATEDBY == null ? 0 : cREATEDBY.hashCode());
        _ret = 29 * _ret + (dATEMODIFIED == null ? 0 : (int)dATEMODIFIED.getTime());
        _ret = 29 * _ret + (mODIFIEDBY == null ? 0 : mODIFIEDBY.hashCode());
        _ret = 29 * _ret + (vMIDSEQ == null ? 0 : vMIDSEQ.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "pVIDSEQ", pVIDSEQ );
        append( sb, "vALUE", vALUE );
        append( sb, "sHORTMEANING", sHORTMEANING );
        append( sb, "mEANINGDESCRIPTION", mEANINGDESCRIPTION );
        append( sb, "bEGINDATE", bEGINDATE );
        append( sb, "eNDDATE", eNDDATE );
        append( sb, "hIGHVALUENUM", hIGHVALUENUM );
        append( sb, "lOWVALUENUM", lOWVALUENUM );
        append( sb, "dATECREATED", dATECREATED );
        append( sb, "cREATEDBY", cREATEDBY );
        append( sb, "dATEMODIFIED", dATEMODIFIED );
        append( sb, "mODIFIEDBY", mODIFIEDBY );
        append( sb, "vMIDSEQ", vMIDSEQ );
    }
}
