/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package nci.cadsr.persist.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import nci.cadsr.persist.dto.DesignationsView;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface DesignationsViewDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public DesignationsView findByPrimaryKey( String dESIGIDSEQ );

    /**
     * Finds a record.
     */
    public DesignationsView findByNAME( String nAME );

    /**
     * Finds records ordered by NAME.
     */
    public DesignationsView[] findAll( );

    /**
     * Deletes a record identified by its primary key.
     * @return true iff the record was really deleted (existed)
     */
    public boolean deleteByPrimaryKey( String dESIGIDSEQ ) throws DaoException;

    /**
     * Inserts a new record.
     * @return the generated primary key - dESIGIDSEQ
     */
    public String insert( DesignationsView dto ) throws DaoException;

    /**
     * Updates one record found by primary key.
     * @return true iff the record was really updated (=found and any change was really saved)
     */
    public boolean update( String dESIGIDSEQ, DesignationsView dto ) throws DaoException;

}
