/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package nci.cadsr.persist.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import nci.cadsr.persist.dto.PermissibleValuesView;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface PermissibleValuesViewDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public PermissibleValuesView findByPrimaryKey( String pVIDSEQ );

    /**
     * Finds a record.
     */
    public PermissibleValuesView findByVALUE( String vALUE );

    /**
     * Finds records ordered by VALUE.
     */
    public PermissibleValuesView[] findAll( );

    /**
     * Deletes a record identified by its primary key.
     * @return true iff the record was really deleted (existed)
     */
    public boolean deleteByPrimaryKey( String pVIDSEQ ) throws DaoException;

    /**
     * Inserts a new record.
     * @return the generated primary key - pVIDSEQ
     */
    public String insert( PermissibleValuesView dto ) throws DaoException;

    /**
     * Updates one record found by primary key.
     * @return true iff the record was really updated (=found and any change was really saved)
     */
    public boolean update( String pVIDSEQ, PermissibleValuesView dto ) throws DaoException;

}
